services:
  mini-neo4j:
    image: neo4j:5.20
    container_name: mini_lab_neo4j
    environment:
      NEO4J_AUTH: neo4j/password
      # We need APOC and GDS for the graph algorithms
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,gds.*"
    ports:
      - "7474:7474" # Browser Interface
      - "7687:7687" # Python Driver Port
    volumes:
      - ./data:/data