services:
  # 1. Postgres
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  # 2. Neo4j
  neo4j:
    image: neo4j:5.20
    environment:
      NEO4J_AUTH: neo4j/password
      # GDS & APOC plugins
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,gds.*"
      NEO4J_server_memory_heap_max__size: 2G
      NEO4J_server_memory_heap_initial__size: 1G
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data

  # 3. Python App
  app:
    image: python:3.11-slim
    working_dir: /work
    volumes:
      - .:/work
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
      POSTGRES_HOST: postgres
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    command: >
      command: bash app/start.sh
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - neo4j